### ISSUE TITLE
Update Number required action fails

### ISSUE THREAD

**Issue by svenseeberg** [netzbegruenung/keycloak-2fa-sms-authenticator#43]
With versions 0.2.1 and 0.2.2 the update phone number required action fails after entering the phone number. No code is being sent and a mail notification about a failed login attempt is being sent to the user.

**Comment by melegiul** [comment]
Error message from the logs:
```
java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 0
+
^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2202)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1068)
	at java.base/java.lang.String.replaceFirst(String.java:2081)
	at netzbegruenung.keycloak.authenticator.gateway.ApiSmsService.clean_phone_number(ApiSmsService.java:143)
```
